graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  playground:
    enabled: true
    mapping: /
    cdn:
      enabled: true
      version: 1.7.20

server:
  port: 9055
